import type { Deck, DeckClass } from "@/lib/types";

export const CURRENT_PATCH = "35.6";

export const CLASS_META: Record<
  DeckClass,
  { short: string; color: string; accent: string; glyph: string }
> = {
  "죽음의 기사": {
    short: "죽기",
    color: "#315766",
    accent: "#8fc2d0",
    glyph: "❄",
  },
  악마사냥꾼: {
    short: "악사",
    color: "#465b2b",
    accent: "#a5d45f",
    glyph: "◈",
  },
  드루이드: {
    short: "드루",
    color: "#7a4b22",
    accent: "#d39a55",
    glyph: "✦",
  },
  사냥꾼: {
    short: "냥꾼",
    color: "#4b6b35",
    accent: "#98c66f",
    glyph: "⌁",
  },
  마법사: {
    short: "법사",
    color: "#2a668b",
    accent: "#77c4e7",
    glyph: "✧",
  },
  성기사: {
    short: "기사",
    color: "#9a6b18",
    accent: "#f0ca64",
    glyph: "☀",
  },
  사제: {
    short: "사제",
    color: "#68656c",
    accent: "#d8d2df",
    glyph: "✚",
  },
  도적: {
    short: "도적",
    color: "#5d4c35",
    accent: "#d4c26b",
    glyph: "◆",
  },
  주술사: {
    short: "술사",
    color: "#315d87",
    accent: "#76aee0",
    glyph: "ϟ",
  },
  흑마법사: {
    short: "흑마",
    color: "#5e3f75",
    accent: "#b48bd2",
    glyph: "◉",
  },
  전사: {
    short: "전사",
    color: "#803d32",
    accent: "#d98673",
    glyph: "✕",
  },
};

export const CLASS_OPTIONS = Object.keys(CLASS_META) as DeckClass[];

export const decks: Deck[] = [
  {
    slug: "tempo-demon-hunter-starter",
    title: "초반부터 밀어붙이는 템포 악마사냥꾼",
    className: "악마사냥꾼",
    archetype: "템포 악마사냥꾼",
    strategy: "템포",
    author: "모닥불지기",
    authorRole: "운영진 큐레이터",
    patch: CURRENT_PATCH,
    patchStatus: "현재 패치",
    evidence: "운영진 확인",
    sourceType: "랭크 덱",
    sourceLabel: "전설 구간 원본 게시물 확인",
    rank: "전설 412위",
    record: "18승 9패",
    difficulty: "쉬움",
    tags: ["초보 추천", "빠른 등반", "쉬운 운영"],
    summary:
      "짧은 게임과 명확한 승리 플랜을 원하는 복귀 유저에게 잘 맞는 공격적인 덱입니다.",
    recommendedFor: "복귀 유저 · 빠르게 등급을 올리고 싶은 유저",
    strengths: ["초반 주도권이 강함", "한 판이 짧음", "운영 목표가 명확함"],
    weaknesses: ["광역기에 취약함", "후반 자원이 빠르게 마름"],
    gamePlan: [
      "1~3턴에는 영웅 공격과 저비용 하수인으로 필드를 먼저 잡습니다.",
      "상대가 정리 카드에 마나를 쓰는 턴에 다시 필드를 채워 압박을 이어갑니다.",
      "중반부터는 모든 교환을 받기보다 남은 피해량을 계산해 영웅을 공격합니다.",
    ],
    mulligan: {
      core: ["불타는 심장", "선봉대 추적자", "혼돈의 일격"],
      situational: ["무리 사냥꾼 — 느린 상대", "칼춤 — 토큰 덱 상대"],
    },
    cardChoices: [
      "선봉대 추적자는 초반 곡선을 안정시키는 핵심 카드입니다.",
      "칼춤 한 장은 필드형 덱이 많은 구간에서 유지합니다.",
    ],
    matchupNotes: [
      "느린 컨트롤 덱을 상대로 유리합니다.",
      "회복과 광역기가 많은 사제에게는 자원을 한 번에 쓰지 마세요.",
    ],
    cards: [
      { cost: 1, name: "불타는 심장", quantity: 2 },
      { cost: 1, name: "선봉대 추적자", quantity: 2 },
      { cost: 1, name: "분노한 신병", quantity: 2 },
      { cost: 2, name: "혼돈의 일격", quantity: 2 },
      { cost: 2, name: "지옥날개 수습생", quantity: 2 },
      { cost: 2, name: "영혼 절단", quantity: 2 },
      { cost: 3, name: "무리 사냥꾼", quantity: 2 },
      { cost: 3, name: "칼춤", quantity: 1 },
      { cost: 3, name: "지옥의 문지기", quantity: 2 },
      { cost: 4, name: "추방자 대장", quantity: 2 },
      { cost: 4, name: "글레이브 투척", quantity: 2 },
      { cost: 5, name: "심연의 추적자", quantity: 2 },
      { cost: 5, name: "격노의 인도자", quantity: 1, legendary: true },
      { cost: 6, name: "군단의 선봉", quantity: 2 },
      { cost: 7, name: "파괴자 브록시가르", quantity: 1, legendary: true },
      { cost: 8, name: "최후의 공세", quantity: 1 },
      { cost: 9, name: "지옥불의 잔향", quantity: 2 },
    ],
    deckCode:
      "AAECAea5Awq2nwTOngaKqgeSqgeTqgfisQeUvwfQvwfUyQeb1AcK4fgF3v8GqocHpYgHtJcHtpcHjb8Hkr8Hlb8H4L8HAAA=",
    recommendations: 238,
    comments: 34,
    copies: 1284,
    trendScore: 92,
    trackingSourceCount: 3,
    lastTrackedAt: "2026.06.07",
    updatedAt: "2026.06.05",
    featuredReason: "복귀 후 첫 덱으로 추천",
  },
  {
    slug: "discover-hunter-flex",
    title: "상황 대응이 즐거운 발견 사냥꾼",
    className: "사냥꾼",
    archetype: "발견 사냥꾼",
    strategy: "미드레인지",
    author: "카드수집가",
    authorRole: "전설 유저",
    patch: CURRENT_PATCH,
    patchStatus: "현재 패치",
    evidence: "출처 연결",
    sourceType: "커뮤니티 덱",
    sourceLabel: "작성자 전적 원본 연결",
    rank: "전설 408위",
    record: "7승 1패",
    difficulty: "보통",
    tags: ["전설 유저", "유연한 운영", "재미"],
    summary:
      "발견 선택으로 매 판 다른 해답을 만들며, 공격과 가치 싸움을 유연하게 오가는 덱입니다.",
    recommendedFor: "선택지가 많은 덱과 즉흥적인 운영을 좋아하는 유저",
    strengths: ["상황 대응력이 높음", "긴 게임에서도 자원 확보", "반복 플레이가 덜 단조로움"],
    weaknesses: ["발견 선택 난이도", "초반 패가 꼬일 수 있음"],
    gamePlan: [
      "초반에는 무리하게 달리기보다 야수와 발견 카드로 손패 품질을 높입니다.",
      "상대 덱을 파악한 뒤 공격 플랜과 장기전 플랜 중 하나를 선택합니다.",
      "고비용 발견 카드는 당장 강한 카드보다 남은 매치업에 필요한 역할을 고릅니다.",
    ],
    mulligan: {
      core: ["추적", "호기심 많은 새끼용", "숲의 안내자"],
      situational: ["폭발 덫 — 공격 덱 상대", "큰 사냥감 — 느린 덱 상대"],
    },
    cardChoices: [
      "추적은 덱의 핵심 카드에 접근하면서 매치업 정보를 보완합니다.",
      "폭발 덫은 공격적인 상대가 많은 구간에서 두 장까지 고려합니다.",
    ],
    matchupNotes: [
      "느린 전사를 상대로 발견 자원을 아끼면 유리합니다.",
      "빠른 악마사냥꾼을 상대로는 가치보다 템포를 우선하세요.",
    ],
    cards: [
      { cost: 1, name: "추적", quantity: 2 },
      { cost: 1, name: "숲의 안내자", quantity: 2 },
      { cost: 2, name: "호기심 많은 새끼용", quantity: 2 },
      { cost: 2, name: "폭발 덫", quantity: 1 },
      { cost: 2, name: "야수 조련", quantity: 2 },
      { cost: 3, name: "갈퀴발톱 동료", quantity: 2 },
      { cost: 3, name: "비밀 탐색가", quantity: 2 },
      { cost: 4, name: "산속 추적자", quantity: 2 },
      { cost: 4, name: "무리의 부름", quantity: 2 },
      { cost: 5, name: "큰 사냥감", quantity: 1 },
      { cost: 5, name: "발견의 대가", quantity: 1, legendary: true },
      { cost: 6, name: "협곡의 포식자", quantity: 2 },
      { cost: 6, name: "별빛 활잡이", quantity: 2 },
      { cost: 7, name: "거대한 추적", quantity: 2 },
      { cost: 8, name: "숲의 군주", quantity: 1, legendary: true },
      { cost: 9, name: "최후의 사냥", quantity: 2 },
      { cost: 10, name: "야생의 메아리", quantity: 2 },
    ],
    deckCode:
      "AAECAaIHBs75A+2ABPbdBMygBeigBeKkBQy9gAT2nwT3nwS3swT03QT13QT87QTBgwXdoAXfoAXgoAXBoQUAAA==",
    recommendations: 171,
    comments: 29,
    copies: 914,
    trendScore: 84,
    trackingSourceCount: 2,
    lastTrackedAt: "2026.06.06",
    updatedAt: "2026.06.04",
    featuredReason: "선택하는 재미가 좋은 덱",
  },
  {
    slug: "aura-paladin-budget",
    title: "가볍게 시작하는 오라 성기사",
    className: "성기사",
    archetype: "오라 성기사",
    strategy: "어그로",
    author: "빛의신병",
    authorRole: "커뮤니티 기여자",
    patch: CURRENT_PATCH,
    patchStatus: "현재 패치",
    evidence: "작성자 입력",
    sourceType: "커뮤니티 덱",
    sourceLabel: "외부 전적 미확인",
    record: "21승 14패",
    difficulty: "쉬움",
    tags: ["초보 추천", "저가루", "쉬운 운영"],
    summary:
      "저비용 하수인을 넓게 전개하고 오라로 강화하는, 직관적이고 비교적 저렴한 입문 덱입니다.",
    recommendedFor: "가루 부담을 줄이고 기본적인 필드 운영을 배우려는 유저",
    strengths: ["저렴한 구성", "필드 전개가 강함", "쉬운 멀리건"],
    weaknesses: ["광역 정리에 취약", "뒤집기 수단이 적음"],
    gamePlan: [
      "매 턴 마나를 남기지 않도록 하수인을 전개합니다.",
      "오라는 최소 두 개 이상의 하수인이 이득을 볼 때 사용합니다.",
      "광역 정리가 예상되면 손의 하수인을 모두 내지 않습니다.",
    ],
    mulligan: {
      core: ["정의로운 수습생", "전장의 악사", "용감한 신병"],
      situational: ["신성한 오라 — 1·2비용 카드가 함께 있을 때"],
    },
    cardChoices: [
      "전설 카드 한 장은 추가 저비용 하수인으로 교체할 수 있습니다.",
      "광역기가 많은 환경에서는 보호막 부여 카드를 늘립니다.",
    ],
    matchupNotes: [
      "초반이 느린 덱을 상대로 빠르게 우위를 만듭니다.",
      "주술사와 사제를 상대로는 두 번째 필드 전개를 준비하세요.",
    ],
    cards: [
      { cost: 1, name: "정의로운 수습생", quantity: 2 },
      { cost: 1, name: "용감한 신병", quantity: 2 },
      { cost: 1, name: "빛의 보호", quantity: 2 },
      { cost: 2, name: "전장의 악사", quantity: 2 },
      { cost: 2, name: "은빛 방패병", quantity: 2 },
      { cost: 2, name: "성전사의 훈련", quantity: 2 },
      { cost: 3, name: "신성한 오라", quantity: 2 },
      { cost: 3, name: "결집의 깃발", quantity: 2 },
      { cost: 3, name: "굳건한 수호자", quantity: 2 },
      { cost: 4, name: "빛벼림 용사", quantity: 2 },
      { cost: 4, name: "전투의 축복", quantity: 2 },
      { cost: 5, name: "황금빛 대장", quantity: 2 },
      { cost: 5, name: "신병대장 리아드린", quantity: 1, legendary: true },
      { cost: 6, name: "빛의 행진", quantity: 2 },
      { cost: 7, name: "백작의 명령", quantity: 1 },
      { cost: 8, name: "최후의 성전", quantity: 2 },
    ],
    deckCode:
      "AAECAZ8FBIbiBKHiBISWBbuXBQ3M6wPw9gPJoAT5pATQrATi0wTa2QS/4gTA4gTy7QSrkwWBlgWDlgUAAA==",
    recommendations: 143,
    comments: 18,
    copies: 1043,
    updatedAt: "2026.06.03",
    featuredReason: "가루 부담이 적은 입문 덱",
  },
  {
    slug: "dragon-warrior-steady",
    title: "단단하게 쌓아가는 용 전사",
    className: "전사",
    archetype: "용 전사",
    strategy: "미드레인지",
    author: "방패와도끼",
    authorRole: "전설 유저",
    patch: CURRENT_PATCH,
    patchStatus: "현재 패치",
    evidence: "출처 연결",
    sourceType: "랭크 덱",
    sourceLabel: "전설 인증 게시물 연결",
    rank: "전설 89위",
    record: "32승 18패",
    difficulty: "보통",
    tags: ["안정적", "전설 유저", "정석 운영"],
    summary:
      "튼튼한 하수인과 효율적인 정리로 필드 우위를 차곡차곡 쌓는 정석형 미드레인지 덱입니다.",
    recommendedFor: "교환과 자원 관리를 배우며 안정적으로 플레이하고 싶은 유저",
    strengths: ["안정적인 마나 곡선", "필드 복구력", "폭넓은 상성"],
    weaknesses: ["극단적인 콤보에 약함", "비교적 높은 제작 비용"],
    gamePlan: [
      "초반에는 무기와 방어도 카드로 상대의 전개를 억제합니다.",
      "중반 용족 하수인을 연속으로 내며 교환 이득을 누적합니다.",
      "후반에는 한 턴에 위협을 몰아내기보다 두 번의 압박을 만듭니다.",
    ],
    mulligan: {
      core: ["초소형 방패", "용의 전령", "철갑 전투원"],
      situational: ["마무리 일격 — 큰 하수인 덱", "소용돌이 — 토큰 덱"],
    },
    cardChoices: ["마무리 일격 수는 환경의 큰 하수인 비중에 맞춥니다."],
    matchupNotes: [
      "일반적인 필드 덱과 고르게 싸웁니다.",
      "콤보 덱에게는 방어보다 압박 속도를 높여야 합니다.",
    ],
    cards: [
      { cost: 1, name: "초소형 방패", quantity: 2 },
      { cost: 2, name: "용의 전령", quantity: 2 },
      { cost: 2, name: "소용돌이", quantity: 1 },
      { cost: 2, name: "철갑 전투원", quantity: 2 },
      { cost: 3, name: "마무리 일격", quantity: 1 },
      { cost: 3, name: "산맥의 수호병", quantity: 2 },
      { cost: 4, name: "붉은비늘 용족", quantity: 2 },
      { cost: 4, name: "방패 강타", quantity: 2 },
      { cost: 5, name: "용의 포효", quantity: 2 },
      { cost: 5, name: "철벽 대장", quantity: 2 },
      { cost: 6, name: "화염비늘 용", quantity: 2 },
      { cost: 6, name: "전선 파괴자", quantity: 2 },
      { cost: 7, name: "산의 어머니", quantity: 1, legendary: true },
      { cost: 7, name: "용군단의 선봉", quantity: 2 },
      { cost: 8, name: "대장군의 함성", quantity: 2 },
      { cost: 9, name: "심장부의 용", quantity: 1, legendary: true },
      { cost: 10, name: "용족의 최후 방어", quantity: 2 },
    ],
    deckCode:
      "AAECAQcGxvMFpfYF2IEGhYIGkagG1boGDN6NBo+oBpKoBpSoBqS7BrrBBtDKBvPKBvTQBqfTBpHmBsGaDAAA",
    recommendations: 119,
    comments: 22,
    copies: 687,
    updatedAt: "2026.06.02",
  },
  {
    slug: "control-priest-patient",
    title: "천천히 판을 뒤집는 컨트롤 사제",
    className: "사제",
    archetype: "컨트롤 사제",
    strategy: "컨트롤",
    author: "긴호흡",
    authorRole: "커뮤니티 기여자",
    patch: CURRENT_PATCH,
    patchStatus: "현재 패치",
    evidence: "작성자 입력",
    sourceType: "커뮤니티 덱",
    sourceLabel: "작성자 입력 기록",
    record: "12승 8패",
    difficulty: "어려움",
    tags: ["컨트롤", "긴 게임", "숙련자 추천"],
    summary:
      "상대의 핵심 위협을 읽고 제거 자원을 배분해, 후반 가치로 역전하는 느린 덱입니다.",
    recommendedFor: "긴 게임과 상대 덱을 읽는 운영을 즐기는 숙련 유저",
    strengths: ["강한 회복", "다양한 제거기", "후반 자원"],
    weaknesses: ["한 판이 김", "선택 난이도가 높음", "콤보 덱에 취약"],
    gamePlan: [
      "상대 덱의 주요 위협 수를 먼저 파악하고 제거기를 배분합니다.",
      "체력 손해를 두려워해 약한 필드에 광역기를 쓰지 않습니다.",
      "후반 생성 카드로 상대의 마지막 자원보다 한 장 더 남기는 것이 목표입니다.",
    ],
    mulligan: {
      core: ["회복의 손길", "빛의 정화", "황혼의 신도"],
      situational: ["대규모 무효화 — 버프 덱", "정신 절단 — 느린 덱"],
    },
    cardChoices: ["공격 덱이 많다면 고비용 생성 카드 한 장을 회복으로 바꿉니다."],
    matchupNotes: [
      "하수인 중심 공격 덱을 상대로 강합니다.",
      "즉시 승리 콤보를 가진 덱에는 먼저 압박할 수단이 부족합니다.",
    ],
    cards: [
      { cost: 1, name: "회복의 손길", quantity: 2 },
      { cost: 2, name: "빛의 정화", quantity: 2 },
      { cost: 2, name: "황혼의 신도", quantity: 2 },
      { cost: 3, name: "정신 절단", quantity: 1 },
      { cost: 3, name: "고통의 전언", quantity: 2 },
      { cost: 4, name: "대규모 무효화", quantity: 1 },
      { cost: 4, name: "성스러운 일격", quantity: 2 },
      { cost: 5, name: "빛의 심판", quantity: 2 },
      { cost: 5, name: "영혼의 인도자", quantity: 2 },
      { cost: 6, name: "황혼의 정화자", quantity: 2 },
      { cost: 6, name: "교단의 수호자", quantity: 2 },
      { cost: 7, name: "대주교의 명령", quantity: 2 },
      { cost: 7, name: "예언자 아만툴", quantity: 1, legendary: true },
      { cost: 8, name: "빛의 소용돌이", quantity: 2 },
      { cost: 9, name: "태양의 화신", quantity: 1, legendary: true },
      { cost: 10, name: "끝없는 기도", quantity: 2 },
      { cost: 10, name: "새벽의 심판", quantity: 2 },
    ],
    deckCode:
      "AAECAa0GCOWwBKi2BMXkBJfvBLvEBf3EBc/GBcXmBQvLoAT52wT/4QT28QT48QSGgwWlkQW7xwXt9wX7+AXpmAYAAA==",
    recommendations: 88,
    comments: 31,
    copies: 432,
    updatedAt: "2026.06.01",
  },
  {
    slug: "rainbow-death-knight-archive",
    title: "무지개 죽음의 기사 기록 보관본",
    className: "죽음의 기사",
    archetype: "무지개 죽음의 기사",
    strategy: "컨트롤",
    author: "룬수집가",
    authorRole: "전설 유저",
    patch: "35.0.3",
    patchStatus: "이전 패치",
    evidence: "출처 연결",
    sourceType: "랭크 덱",
    sourceLabel: "이전 패치 원본 연결",
    rank: "전설 203위",
    record: "24승 13패",
    difficulty: "보통",
    tags: ["이전 패치", "기록 보관", "컨트롤"],
    summary:
      "이전 밸런스 패치에서 좋은 성적을 낸 구성입니다. 현재 메타에서는 카드 교체가 필요할 수 있습니다.",
    recommendedFor: "이전 구성과 현재 리스트의 차이를 살펴보려는 유저",
    strengths: ["다양한 해답", "후반 가치", "안정적인 회복"],
    weaknesses: ["현재 패치 미검증", "운영 선택지가 많음"],
    gamePlan: ["룬별 핵심 카드를 상황에 맞게 배분하며 후반까지 자원을 유지합니다."],
    mulligan: {
      core: ["시체 자루", "서리의 손길", "역병 전달자"],
      situational: ["피의 소용돌이 — 공격 덱 상대"],
    },
    cardChoices: ["현재 패치 카드 풀과 일치하는지 복사 전 확인하세요."],
    matchupNotes: ["현재 패치의 상성 정보는 확인되지 않았습니다."],
    cards: [
      { cost: 1, name: "시체 자루", quantity: 2 },
      { cost: 2, name: "서리의 손길", quantity: 2 },
      { cost: 2, name: "역병 전달자", quantity: 2 },
      { cost: 3, name: "피의 소용돌이", quantity: 2 },
      { cost: 3, name: "룬벼림 병사", quantity: 2 },
      { cost: 4, name: "시체 수확자", quantity: 2 },
      { cost: 4, name: "얼어붙은 무덤", quantity: 2 },
      { cost: 5, name: "무지개 봉합", quantity: 2 },
      { cost: 5, name: "영혼 포식자", quantity: 2 },
      { cost: 6, name: "역병의 기사", quantity: 2 },
      { cost: 6, name: "서리 여왕", quantity: 1, legendary: true },
      { cost: 7, name: "시체 거인", quantity: 2 },
      { cost: 7, name: "룬의 지배자", quantity: 1, legendary: true },
      { cost: 8, name: "죽음의 행진", quantity: 2 },
      { cost: 9, name: "리치의 부름", quantity: 2 },
      { cost: 10, name: "최후의 역병", quantity: 2 },
    ],
    deckCode:
      "AAECAfHhBAb8owP39gOzoAScmgb8wAaKqgcM1MgD8skD1tEDztID9fYDivcDtKAEiJIFlJIF4fgF38AGwpoMAAA=",
    recommendations: 76,
    comments: 15,
    copies: 391,
    updatedAt: "2026.05.22",
  },
];

export function getDeck(slug: string) {
  return decks.find((deck) => deck.slug === slug);
}

export function getFeaturedDecks() {
  return decks.filter((deck) => deck.featuredReason).slice(0, 3);
}

export function getPopularDecks() {
  return [...decks]
    .filter((deck) => deck.patchStatus === "현재 패치")
    .sort((a, b) => b.copies - a.copies)
    .slice(0, 4);
}

export function getBeginnerDecks() {
  return decks
    .filter((deck) => deck.tags.includes("초보 추천"))
    .slice(0, 3);
}
